# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

general:
  branches:
    only:
      # Circle CI only care with following branches. (eg. "master")
      - master
jobs:
  build:
    docker:
      # specify the version you desire here
      #- image: circleci/openjdk:8-jdk

      # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/android:api-28-alpha

    # Ini adalah direktori project
    working_directory: ~/poken-android

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
#      KEYSTORE: ${CIRCLE_WORKING_DIRECTORY}/sigining.keystore
#      PUBLISHER_ACCT_JSON_FILE: ${CIRCLE_WORKING_DIRECTORY}/publisher_profile.json

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Memastikan gradlew bisa di run
      - run:
            name: chmod permissions
            command: chmod +x ./gradlew

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # build production release
      - run: ./gradlew --profile --recompile-scripts --rerun-tasks :app:assembleProductionRelease

      - store_artifacts:
          path: app/build/outputs/apk/
          destination: apk

      - store_artifacts:
          path: app/build/outputs/mapping/
          destination: mapping

      - store_artifacts:
          path: build/reports/profile/
          destination: profile